

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-hugo:       # This job runs in the build stage, which runs first.
  stage: build
  image: debian
  before_script:
    - apt update
    - apt full-upgrade -y
    - apt install -y go hugo 
  script:
    - ls
    - echo "Compile complete."


