

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

hugo-build:       # This job runs in the build stage, which runs first.
  stage: build
  image: chainguard/hugo
  script:
    - ls
    - echo "Compile complete."


